modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "${mod_id}.png"
description = '''
Astral Warfare - An epic boss fight mod featuring the Stella Evoker.
'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "lodestone"
type = "required"
versionRange = "[1.7,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "curios"
type = "required"
versionRange = "[9.0,)"
ordering = "AFTER"
side = "BOTH"
